---
name: "Permify Schema Validate Action"
description: "Runs the `permify validate` command on the given schema validation file."
author: "Permify"

inputs:
  validationFile:
    description: "path to the YAML file containing schema (authorization model), relationships (sample authorization data), assertions (sample check queries and results)."
    required: true
    default: '/schemas'

runs:
  using: "docker"
  image: "Dockerfile"