---
name: "test"

on:
  - "push"
  - "pull_request"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "./"
        with:
          validationFile: "./tests/sample-schema.yaml"