---
name: "test"

on:
  push:
  pull_request:

jobs:
  test1:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "./"
        with:
          validationFile: "./tests/sample-schema.yaml"

  test2:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "./"
        with:
          validationFile: "./tests/schemas/sample-schema-with-file-path.yaml"
